name: taxee_client
description: A route plotter for Elite:` Dangerous
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  angular: 7.0.2

dev_dependencies:
  angular_test: 4.0.1
  build_runner: ^2.1.4
  build_test: 2.1.5
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  test: 1.19.2
